#!/bin/sh /etc/rc.common

START=50

start() {
    (cd /www/autonta/lua; ./run_uhttpd_server.sh >& /tmp/an_start.log&)
}

stop() {
    if [ -e /var/autonta.pid ]; then
        kill `cat /var/autonta.pid`
        # Wait until pid disappears
        while [ -e /var/autonta.pid ]; do
            sleep 1
        done
    fi
}

reload() {
    if [ -e /var/autonta.pid ]; then
        kill `cat /var/autonta.pid`
        # Wait until pid disappears
        while [ -e /var/autonta.pid ]; do
            sleep 1
        done
    fi
    (cd /www/autonta/lua; ./run_uhttpd_server.sh >& /tmp/an_start.log&)
}

restart() {
    if [ -e /var/autonta.pid ]; then
        kill `cat /var/autonta.pid`
        # Wait until pid disappears
        while [ -e /var/autonta.pid ]; do
            sleep 1
        done
    fi
    (cd /www/autonta/lua; ./run_uhttpd_server.sh >& /tmp/an_start.log&)
}

shutdown() {
    if [ -e /var/autonta.pid ]; then
        kill `cat /var/autonta.pid`
        # Wait until pid disappears
        while [ -e /var/autonta.pid ]; do
            sleep 1
        done
    fi
}

