#!/bin/sh /etc/rc.common
#Copyright (C) 2010 Ondrej Caletka <o.caletka@sh.cvut.cz>
START=61

start () {
    # unbound will fail to start if the interface isn't completely up yet
    # Note: is this link-local always the same?
    /sbin/wait_for_if.sh br-lan fd48:430c:f4bc::1
    unbound
}

stop () {
    PIDFILE='/var/run/unbound.pid'
    if [ -f $PIDFILE ] ; then
        kill $(cat $PIDFILE)
    fi
}
