#!/bin/sh /etc/rc.common

START=85

SPIN_SERVER_PID="/var/run/spin_collectd.pid"

run_spin_server() {
    cd /usr/lib/spin
    lua ./spin_mqtt.lua&
    echo $! > ${SPIN_SERVER_PID}
}

apply_spin_config() {
    cd /usr/lib/spin
    lua ./spin_config.lua apply_config
}

start() {
    insmod /usr/lib/spin/spin.ko
    apply_spin_config
    run_spin_server
}

stop() {
    if [ -e ${SPIN_SERVER_PID} ]; then
        kill `cat ${SPIN_SERVER_PID}`
        rm ${SPIN_SERVER_PID}
    fi
    rmmod spin
}

restart() {
    stop
    start
}

reload() {
    stop
    start
}
