#!/bin/sh /etc/rc.common

START=85

SPINWEB_SERVER_PID="/var/run/spinweb.pid"

spin_server_running() {
    if [ -e ${SPINWEB_SERVER_PID} ]; then
        ps w | grep ${SPINWEB_SERVER_PID} | grep spinweb 2>&1 > /dev/null
        [ $? == 0 ]
    else
        false
    fi
}

run_spin_server() {
    /usr/bin/spinweb&
    echo $! > ${SPINWEB_SERVER_PID}
}

stop_spin_server() {
    if [ -e ${SPINWEB_SERVER_PID} ]; then
        kill -9 `cat ${SPINWEB_SERVER_PID}`
        rm ${SPINWEB_SERVER_PID}
    fi
}

load_spin_modules() {
    modprobe nf_conntrack
    modprobe nf_conntrack_ipv4
    modprobe nf_conntrack_ipv6
    modprobe nf_netlink_queue
    sysctl net.netfilter.nf_conntrack_acct=1
}

spin_modules_loaded() {
    lsmod | grep spin 2>&1 > /dev/null
    [ $? == 0 ]
}

start() {
    if spin_server_running; then
        echo "SPIN server already running"
    else
        echo "SPIN server not running"
        run_spin_server
    fi
}

stop() {
    stop_spin_server
}

restart() {
    stop
    start
}

reload() {
    stop
    start
}

enable() {
    ln -s /etc/init.d/spin /etc/rc.d/S${START}spin
    start
}

disable() {
    rm -f /etc/rc.d/S${START}spin
    stop
}
