#!/bin/sh /etc/rc.common

START=85

SPINWEB_SERVER_PID="/var/run/spinweb.pid"

spinweb_server_running() {
    if [ -e ${SPINWEB_SERVER_PID} ]; then
        ps w | grep ${SPINWEB_SERVER_PID} | grep spinweb 2>&1 > /dev/null
        [ $? == 0 ]
    else
        false
    fi
}

run_spinweb_server() {
    /usr/bin/spinweb&
    echo $! > ${SPINWEB_SERVER_PID}
}

stop_spinweb_server() {
    if [ -e ${SPINWEB_SERVER_PID} ]; then
        kill -9 `cat ${SPINWEB_SERVER_PID}`
        rm ${SPINWEB_SERVER_PID}
    fi
}

start() {
    if spinweb_server_running; then
        echo "SPINweb server already running"
    else
        echo "SPINweb server not running"
        run_spinweb_server
    fi
}

stop() {
    stop_spinweb_server
}

restart() {
    stop
    start
}

reload() {
    stop
    start
}

enable() {
    ln -s /etc/init.d/spin /etc/rc.d/S${START}spinweb
    start
}

disable() {
    rm -f /etc/rc.d/S${START}spinweb
    stop
}
